import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import { marked } from 'marked'
import Layout from '../../components/layout'
import Image from 'next/image'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { AiOutlineClockCircle } from 'react-icons/ai'

export default function PostPage(props) {
  const [windowWidth, setWindowWidth] = useState(0)
  const [windowHeigth, setWindowHeigth] = useState(0)
  useEffect(() => {
    setWindowWidth(window.innerWidth)
    setWindowHeigth(window.innerHeight)
  }, [])
  return <>
    <Head>
      <title>{props.frontmatter.title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <div className=''>
      <span className="uppercase text-md text-gray-600 block my-5"><AiOutlineClockCircle className="text-xl inline-block text-gray-400 mr-3" />{props.frontmatter.minutes} de leitura</span>
        <Image width={windowWidth} height={500} className='rounded-md' alt="props.slug" src={props.frontmatter.cover_image} />
        <div className=''>
          <span className="mx-auto table uppercase p-3 font-semibold text-gray-600">{props.frontmatter.date}</span>
          <h1 className="font-bold text-xl md:text-3xl text-center text-gray-800">{props.frontmatter.title}</h1>
          <p>{props.frontmatter.description}</p>
          <div dangerouslySetInnerHTML={{ __html: marked(props.content) }}></div>
        </div>
      </div>
    </Layout></>
}

export async function getStaticPaths() {
  const files = fs.readdirSync(path.join('posts'))
  const paths = files.map(filename => ({
    params: {
      slug: filename.replace('.md', '')
    }
  }))

  return {
    paths,
    fallback: false
  }
}

export async function getStaticProps({ params: { slug } }) {
  const markdownWithMeta = fs.readFileSync(path.join('posts', slug + '.md'))

  const { data: frontmatter, content } = matter(markdownWithMeta)
  return {
    props: {
      content,
      frontmatter,
      slug
    }
  }
}