import Head from 'next/head'
import {  useEffect, useState } from 'react'
import Layout from '../components/layout'
import Post from '../components/post'
import getAllPosts from '../scripts/getAllPosts'


export default function Home({ posts }) {
  const [postList, setPostList] = useState([])
  
  useEffect(() => {
    setPostList(posts)
  },[posts])
  
  const categories = []
  posts.map(post => {
    const category = post.frontmatter.category
    const findCategory = categories.findIndex(cat => {
      return cat.category == category
    })
    if (findCategory < 0) {
      categories.push({ category, post: [post] })
    } else {
      categories[findCategory] = {
        ...categories[findCategory],
        post: [...categories[findCategory].post, post]
      }
    }
  })
  return (
    <div>
      <Head>
        <title>Simple Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className='flex items-center justify-center'>
        <span onClick={() => setPostList(posts)} className='p-2 bg-gray-900 hover:bg-gray-800 transition-colors mx-2 rounded-sm text-white select-none cursor-pointer'>Todos</span>
          {categories.map(cat => {
            return <span onClick={() => setPostList(cat.post)} className='p-2 bg-gray-900 hover:bg-gray-800 transition-colors mx-2 rounded-sm text-white select-none cursor-pointer' key={cat.category}>{cat.category} </span>
          }
          )}
        </div>
        <div className='md:grid md:grid-cols-3 gap-5 mt-3 md:mt-5'>
          {postList.map(p => <Post key={p.slug} post={p} />)}
        </div>
      </Layout>

    </div>
  )
}

export async function getStaticProps() {
  const posts = getAllPosts()
  return {
    props: {
      posts: posts
    }
  }
}